### PR TITLE
Read cpmd

### LINKED ISSUE #23: CPMD Overlaps to PDB/GRO
Convert the overlap from the CPMD input file back to a .pdb or .gro file for visual inspection (similar to gmx editconf -n index with QMatoms)

### LINKED ISSUE #25: Reading CPMD input script not working
Reading of CPMD input script from string/file is not working for many cases. Need to debug and test more

### PR DESCRIPTION
**Pull request by bharurn**
Fixes #23 and fixes #25.
Please try with some input files (CONSTRAINTS in the ATOMS section not supported)

### CODE REVIEW

**Review by fschackert — CHANGES_REQUESTED** [review]
- `section_reg` in line 162 in `cpmd.py` does not support leading blanks. Please add that.
- Distances in the output coordinate file are too big. I guess unit conversion is wrong ... or my input files (please let it be the conversion)

**Comment by bharurn** [comment]
Regarding point 1, do you mean blanks before the section name. If so, the regex already takes care of that. Anyways, I added an extra check for that.
Regards point 2, it was a unit conversion error. I fixed that.

**Comment by fschackert** [comment]
Regarding point 1)
Oh, then it is not the section but the keywords within a section which are not recognized with leading blanks.
This is the error message I get:

` 	                ***** MiMiCPy *****                  

 	 For more information type mimicpy [subcommand] --help 

=====> Running cpmd2coords <=====


**Reading topology**

Cannot find path to Gromacs installation
Could not find ../restraints/PROA_rest.itp. Skipping.
Could not find ../restraints/PROB_rest.itp. Skipping.
Could not find ../restraints/PROC_rest.itp. Skipping.
Could not find ../restraints/PROD_rest.itp. Skipping.
Could not find ../restraints/POPC_rest.itp. Skipping.

**Writing coordinates**  |No OVERLAPS in MIMIC section found
`

Regarding point 2)
Looks good!

**Comment by bharurn** [comment]
Please check if the new commit fixes point 1.

**Comment by fschackert** [comment]
Point 1 fixed.

**Review by fschackert — COMMENTED** [review]
Some other things:
- coords/base.py line 12: Why is it `self.file` and not just `file` ?
- coords/base.py line 27: `else` after `return`
- scripts/cpmd.py: pylint rating of 3.29/10. I think we should have a closer look at this.
- scripts/script.py: Inconsistent assignment `self.__setattr__('__orddict__', OrderedDict())` vs `self.__orddict__ = OrderedDict()`

**Comment by fschackert** [comment]
#25 is still up to date and will not be fixed by this pr.

**Comment by fschackert** [comment]
Looks all good!

**Review by fschackert — APPROVED** [review]

**Pull request merged**
